name: Publish Nuget package
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        
      - name: Create new Semantic Version
        id: next_version
        uses: zwaldowski/semver-release-action@v1
        with:
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      
      - name: Build
        run: dotnet build -c Release Src/Dister.Net
      
      - name: Pack
        run: dotnet pack -c Release -p:Version=${{ steps.next_version.outputs.version }} -o nuget Src/Dister.Net
      
      - name: Publish
        run: dotnet nuget push nuget/*.nupkg -k ${{secrets.NugetAPIKey}}
